version: 0.0
os: linux

# files that should be deployed
files:
  - source: /
    destination: /opt/application/

# mandatory hooks
hooks:
  BeforeInstall:
    - location: bin/stop.sh
      timeout: 3600
  ApplicationStart:
    - location: bin/start.sh
      timeout: 3600
  ValidateService:
    - location: bin/validate.sh
      timeout: 3600